#!/bin/bash
. /etc/conf.d/eeepc-1015pem-acpi.conf

# Function used to send a notification, checking the
# conf file, to choose the right notification system
notify() {
if [ ! a$NOTIFY_DE = "a" ] ; then
  case $1 in
    if [ $NOTIFY_DE = "gtk" ] ; then
      touchpad) su $USER -c "notify-send 'Touchpad' '$touch_not'" ;;
      she) su $USER -c "notify-send 'SHE:' '$old --> $new'" ;;
    else if [ $NOTIFY_DE = "qt" ] ; then
      touchpad) su $USER -c "kdialog --passivepopup '$touch_not' --title 'Touchpad'"
      she) su $USER -c "kdialog --passivepopup '$old --> $new' --title 'SHE:'"
    else
      echo -e "You have setted a wrong value in conf file!"
      exit 1
    fi
  esac
fi
}

# Function to toggle the FSB clock through
# the Asus Super Hybrid Engine
she_toggle() {
SHE_DIR="/sys/devices/platform/eeepc/cpufv"
export DISPLAY=:0

if [ a$1 = "a" ] ; then
  case "$(cat $SHE_DIR)" in
    0x300)	# To Powersave
      echo 2 > $SHE_DIR
      new="Powersave"
      old="Performance"
      notify she
    ;;
    0x301)	# To Performance 
      echo 0 > $SHE_DIR
      new="Performance"
      old="Normal"
      notify she
    ;;
    0x302)	# To Normal
      echo 1 > $SHE_DIR
      new="Normal"
      old="Powersave"
      notify she
    ;;
    *)
      echo 1 > $SHE_DIR
      old=""
      notify she
    ;;
  esac
else
  case $1 in
    powersave) echo 2 > $SHE_DIR ;;
    normal) echo 1 > $SHE_DIR ;;
    performance) echo 0 > $SHE_DIR ;;
  esac
fi
}

#Function to toggle the touchpad, via synclient (xf86-input-synaptics)
touchpad_toggle() {
TOUCH_STATUS=`synclient | grep TouchpadOff | awk '{print $3}'`

if [ $TOUCH_STATUS = 0 ] ; then
  synclient TouchpadOff=1
  touch_not="disabled"
  notify touchpad
else
  synclient TouchpadOff=0
  touch_not="enabled"
  notify touchpad
fi
}
